class Locators():

    #login page object
    username_textbox_id = "username"
    password_textbox_id = "password"
    login_button_id = "Login"

    #new pop up
    new_button_absXpath = "/html[1]/body[1]/div[4]/div[1]/section[1]/div[1]/div[2]/div[2]/div[1]/div[1]/div[1]/div[1]/div[1]/div[1]/div[1]/div[1]/div[1]/div[1]/div[1]/div[1]/div[1]/div[1]/div[1]/div[1]/div[2]/div[1]/div[1]/div[1]/div[2]/ul[1]/li[1]/a[1]/div[1]"
    component_item_name_absXpath = "/html[1]/body[1]/div[4]/div[2]/div[1]/div[2]/div[1]/div[2]/div[1]/div[1]/div[1]/records-lwc-detail-panel[1]/records-base-record-form[1]/div[1]/div[1]/div[1]/div[1]/records-record-layout-event-broker[1]/slot[1]/records-lwc-record-layout[1]/forcegenerated-detailpanel_sheep_obj_system__c___012000000000000aaa___full___create___recordlayout2[1]/force-record-layout-block[1]/slot[1]/force-record-layout-section[1]/div[1]/div[1]/div[1]/slot[1]/force-record-layout-row[1]/slot[1]/force-record-layout-item[1]/div[1]/span[1]/slot[1]/slot[1]/force-record-layout-base-input[1]/lightning-input[1]/div[1]/input[1]"
    situation_box_absXpath = "/html[1]/body[1]/div[4]/div[2]/div[1]/div[2]/div[1]/div[2]/div[1]/div[1]/div[1]/records-lwc-detail-panel[1]/records-base-record-form[1]/div[1]/div[1]/div[1]/div[1]/records-record-layout-event-broker[1]/slot[1]/records-lwc-record-layout[1]/forcegenerated-detailpanel_sheep_obj_system__c___012000000000000aaa___full___create___recordlayout2[1]/force-record-layout-block[1]/slot[1]/force-record-layout-section[1]/div[1]/div[1]/div[1]/slot[1]/force-record-layout-row[1]/slot[1]/force-record-layout-item[2]/div[1]/span[1]/slot[1]/slot[1]/force-record-picklist[1]/force-form-picklist[1]/lightning-picklist[1]/lightning-combobox[1]/div[1]/lightning-base-combobox[1]/div[1]/div[1]/input[1]"
    situation_select_absXpath = "/html[1]/body[1]/div[4]/div[2]/div[1]/div[2]/div[1]/div[2]/div[1]/div[1]/div[1]/records-lwc-detail-panel[1]/records-base-record-form[1]/div[1]/div[1]/div[1]/div[1]/records-record-layout-event-broker[1]/slot[1]/records-lwc-record-layout[1]/forcegenerated-detailpanel_sheep_obj_system__c___012000000000000aaa___full___create___recordlayout2[1]/force-record-layout-block[1]/slot[1]/force-record-layout-section[1]/div[1]/div[1]/div[1]/slot[1]/force-record-layout-row[1]/slot[1]/force-record-layout-item[2]/div[1]/span[1]/slot[1]/slot[1]/force-record-picklist[1]/force-form-picklist[1]/lightning-picklist[1]/lightning-combobox[1]/div[1]/lightning-base-combobox[1]/div[1]/div[2]/lightning-base-combobox-item[3]"
    Account_box_absXpath = "//force-record-layout-section[5]/div/div/div/slot/force-record-layout-row/slot/force-record-layout-item/div/span/slot/slot/force-record-layout-lookup/lightning-lookup/lightning-lookup-desktop/lightning-grouped-combobox/div/div/lightning-base-combobox/div/div/input"
    Account_Select_absXpath = "/html[1]/body[1]/div[4]/div[2]/div[1]/div[2]/div[1]/div[2]/div[1]/div[1]/div[1]/records-lwc-detail-panel[1]/records-base-record-form[1]/div[1]/div[1]/div[1]/div[1]/records-record-layout-event-broker[1]/slot[1]/records-lwc-record-layout[1]/forcegenerated-detailpanel_sheep_obj_system__c___012000000000000aaa___full___create___recordlayout2[1]/force-record-layout-block[1]/slot[1]/force-record-layout-section[5]/div[1]/div[1]/div[1]/slot[1]/force-record-layout-row[1]/slot[1]/force-record-layout-item[1]/div[1]/span[1]/slot[1]/slot[1]/force-record-layout-lookup[1]/lightning-lookup[1]/lightning-lookup-desktop[1]/lightning-grouped-combobox[1]/div[1]/div[1]/lightning-base-combobox[1]/div[1]/div[2]/ul[1]/li[1]/lightning-base-combobox-item[1]/span[2]/span[1]/lightning-base-combobox-formatted-text[1]"
    save_item_absXpath ="/html[1]/body[1]/div[4]/div[2]/div[1]/div[2]/div[1]/div[2]/div[1]/div[1]/div[1]/records-lwc-detail-panel[1]/records-base-record-form[1]/div[1]/div[1]/div[1]/force-form-footer[1]/div[1]/lightning-button[3]/button[1]"
    close_new_item = "/html[1]/body[1]/div[4]/div[1]/section[1]/div[1]/div[1]/one-appnav[1]/div[1]/one-app-nav-bar[1]/nav[1]/div[1]/one-app-nav-bar-item-root[6]/button[1]"